#!/bin/bash
#PBS -l select=1:ncpus=24
#PBS -l walltime=24:00:00
#PBS -q smp
#PBS -P CBBI1243
#PBS -o /mnt/lustre/groups/CBBI1243/KEVIN/git/GWAS/analysis/emmax/stdout.txt
#PBS -e /mnt/lustre/groups/CBBI1243/KEVIN/git/GWAS/analysis/emmax/stderr.txt
#PBS -N EMMAX
#PBS -M kevin.esoh@students.jkuat.ac.ke
#PBS -m b


module add chpc/BIOMODULES
module load plink/1.90
module load gnu/parallel-20160422
module load R/3.6.3

cd /mnt/lustre/groups/CBBI1243/KEVIN/git/GWAS/analysis/emmax/

#--- Without gene list
./runAllassoc.sh

