#!/bin/bash
#PBS -l select=1:ncpus=24
#PBS -l walltime=24:00:00
#PBS -q smp
#PBS -P CBBI1243
#PBS -o /mnt/lustre/groups/CBBI1243/KEVIN/git/GWAS/popstruct/alder/stdout.txt
#PBS -e /mnt/lustre/groups/CBBI1243/KEVIN/git/GWAS/popstruct/alder/stderr.txt
#PBS -N ALDER
#PBS -M kevin.esoh@students.jkuat.ac.ke
#PBS -m b

module add chpc/BIOMODULES
module load samtools/1.9
module add gnu/parallel-20160422
module load bcftools/1.6.33
module load EIGENSOFT/6.1.3
module load alder/1.03
module load plink/1.90 
module load R/3.6.0-gcc7.2.0

cd /mnt/lustre/groups/CBBI1243/KEVIN/git/GWAS/popstruct/alder/

./alder.sh
#malder -p world-alder.par 2>&1 | tee alder.log.out
