#!/bin/bash
#PBS -l select=1:ncpus=24
#PBS -l walltime=96:00:00
#PBS -q smp
#PBS -P CBBI1243
#PBS -o /mnt/lustre/groups/CBBI1243/KEVIN/git/GWAS/popstruct/admixture/stdout.txt
#PBS -e /mnt/lustre/groups/CBBI1243/KEVIN/git/GWAS/popstruct/admixture/stderr.txt
#PBS -N ADMX
#PBS -M kevin.esoh@students.jkuat.ac.ke
#PBS -m b

module add chpc/BIOMODULES
module add gnu/parallel-20160422
module load bcftools/1.6.33
module load EIGENSOFT/6.1.3
module load alder/1.03
module load plink/1.90 
module load R/3.6.0-gcc7.2.0
module load admixture/1.3.0

cd /mnt/lustre/groups/CBBI1243/KEVIN/git/GWAS/popstruct/admixture

./run_admixture.sh world 4 14 2>&1 | tee world.log.out
