#!/bin/bash

home="$HOME/Git/GWAS/"
ana="${home}analysis/"
kgp="${home}1000G/"

# chr16_imputed.gen.include_r2_0.5

qct2gen() {
if [[ $# != 4 ]]; then
   echo """
   Usage: ./qct2gen.sh <hardcall_threshold> <sample_file> <outprefx> <info>
   """
else
   hc=$1
   sf="$2"
   op=$3
   info=$4
   if [[ -f merge.list ]]; then
       rm merge.list
   fi
   for chr in {1..22}; do
     qctool_v2.0.1 \
      -g chr${chr}_imputed.gen.gz \
      -s $sf \
      -og chr${chr}_temp.vcf \
      -os chr${chr}_imputed.sample \
      -precision 1 \
      -threshold $hc \
      -assume-chromosome $chr \
      -threads 60 \
      -incl-rsids chr${chr}_imputed.gen.include_r2_${info} \
      -ofiletype vcf \
      -sort
     bgzip -f -@ 30 chr${chr}_temp.vcf
     bcftools index --threads 50 -f -t chr${chr}_temp.vcf.gz
     bcftools annotate -c CHROM,POS,ID,REF,ALT,INFO/VT -a ${kgp}Phase3_merged.vcf.gz chr${chr}_temp.vcf.gz | \
         bcftools view -e 'INFO/VT!="SNP"' --threads 30 -Oz -o chr${chr}_imputed.vcf.gz
   done
   bcftools concat --threads 30 -D -a -Oz -o ${op}.r2_${info}.vcf.gz chr{1..22}_imputed.vcf.gz
fi
}
